### PR TITLE
Add Debian Support

### PR DESCRIPTION
**Pull request by to-kn**
Since this fails on Debian with the following errors:

Notice: There are no params for Debian yet.
Notice: /Stage[main]/Puppet::Params/Notify[There are no params for Debian yet.]/message: defined 'message' as 'There are no params for Debian yet.'
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/server]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/parser]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/ordering]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/pluginsync]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/logdir]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/vardir]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/ssldir]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ main/rundir]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/certname]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/show_diff]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/splay]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/configtimeout]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/usecacheonfailure]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/report]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ agent/environment]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ master/ca]: Could not evaluate: can't convert nil into String
Error: /Stage[main]/Puppet::Config/Ini_setting[ master/ssldir]: Could not evaluate: can't convert nil into String

i updated params.pp to match for Debian Systems also.

### CODE REVIEW

**Comment by jtopjian** [comment]
Nice - thank you for testing this out.

Since the parameters are the same, `$::lsbdistid` can just be changed to `$::osfamily` and the same block can be re-used.

**Comment by jtopjian** [comment]
I just added support for this in 4e71f4490. Let me know if you're still having problems with Debian.

Thank you again for bringing this issue up. :smile:

**Comment by to-kn** [comment]
Hi, you missed config.pp as far as i can see.

**Comment by jtopjian** [comment]
You're absolutely right - I apologize. Also, Github never notified me about the additional commits you made. I'm really sorry about that as I would have used your pull request!

**Pull request closed without merging**
